### ISSUE TITLE
xbrl-xml2json problem in Instance()

### ISSUE THREAD

**Issue by FabioMezzo** [data-lane/xbrl-xml2json#1]
Hi, I'm a junior back-end developer and I'm using xbrl-xml2json library. I have a problem with the Instance.php in processElements() function at isset() condition closing at 407row, I don't know the reason but a $fact disappears. But before 407 row closing, this fact is inside $facts array. 

for example:
print_f($fact['dimensions']) before
<code> 
   [f37104] => Array
        (
            [value] => 114972
    
            [decimals] => 0
            [dimensions] => Array
                (
                    [concept] => itcc-ci:XxxYyyyKkkkkkkkk
                    [entity] => scheme:xxxxxxxxxxx
                    [period] => 20xx-0x-0xT00:00:00
                    [unit] => xxxxx:XXX
                )

        )

 [f37103] => Array
        (
            [value] => 469234
    
            [decimals] => 0
            [dimensions] => Array
                (
                    [concept] => itcc-ci:XxxYyyyKkkkkkkkk
                    [entity] => scheme:xxxxxxxxxxx
                    [period] => 20xx-0x-0xT00:00:00
                    [unit] => xxxxx:XXX
                )

        )

</code>

print_f($fact['dimensions']) after

<code>
   [f37104] => Array
        (
            [value] => 114972
    
            [decimals] => 0
            [dimensions] => Array
                (
                    [concept] => itcc-ci:XxxYyyyKkkkkkkkk
                    [entity] => scheme:xxxxxxxxxxx
                    [period] => 20xx-0x-0xT00:00:00
                    [unit] => xxxxx:XXX
                )

        )
</code>

In the second example there isn't f37103's fact. Why can this happen? Any idea?

**Comment by FabioMezzo** [comment]
print_r(), not print_f(). I'm sorry

**Comment by vladsrynty** [comment]
Do you have original xbrl to test with?

**Comment by vladsrynty** [comment]
No response
